# site settings

title: Dan McCabe, Ph.D.
description: Personal website for Dan McCabe
taglong: Optimization and data science for sustainable transportation
tagshort: Sustainable transportation engineer
url: https://dan-mccabe.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/dan-mccabe/dan-mccabe.github.io

# author settings

author:
  name: Dan McCabe
  email: dmccabe@uw.edu
photo: /McCabeHeadshot.jpg

# social media links

social:
  github: dan-mccabe
  linkedin: danielpmccabe

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
