# site settings

title: Dan McCabe
description: Personal website for Dan McCabe
taglong: PhD Student, CEE, University of Washington
tagshort: University of Washington
url: https://dan-mccabe.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/dan-mccabe/dan-mccabe.github.io

# author settings

author:
  name: Dan McCabe
  email: dmccabe@uw.edu
photo: /McCabeHeadshot.jpg

# social media links

social:
  github: dan-mccabe
  linkedin: danielpmccabe

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-analytics

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: G-4MPY3RLL6E        # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
